version: "3.8"

services:
  web:
    build: .
    container_name: casa0017
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Mount the DB file from host â†’ container
      - ./server/db/eco_env.sqlite:/website/server/db/eco_env.sqlite
  
